// client-tva-fix.js
// Fix: Client Target vs Achievement tab not rendering
// Author: Auto-generated by M365 Copilot
// Date: 2026-05-03

function renderClientTVA(data) {
  // Preserve existing state
  const originalFilters = JSON.parse(JSON.stringify(filters));
  const originalPage = currentPage;

  // Force TVA mode
  currentPage = 'tva';

  // Remove coordinator filter for client safety
  if (filters && filters.coord) {
    filters.coord = [];
  }

  // Render existing TVA logic
  renderTVA(data);

  // Remove coordinator-specific UI elements if any
  document.querySelectorAll('.coord-strip, .coord-only').forEach(el => el.remove());

  // Restore original state
  filters = originalFilters;
  currentPage = originalPage;
}

// Patch client tab router
const originalRenderClientView = renderClientView;
renderClientView = function() {
  const data = getClientData();
  if (clientTab === 'tva') {
    renderClientTVA(data);
  } else {
    renderClientProgDash(data);
  }
};
